### ISSUE TITLE
GitHub no longer supports the git protocol.

### ISSUE THREAD

**Issue by kNoAPP** [tekartik/chrome_travis.dart#4]
Please read:
https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

This issue also effects the entire dependency tree dependent on this library. So its important to make this change before March.

In your pubspec.yml file, you need to change the
```
tekartik_lints:
    git:
      url: git://github.com/tekartik/common.dart
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'
```
to
```
tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart.git
      ref: null_safety
      path: packages/lints
    version: '>=0.1.0'
```
